server:
  port: 8050
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: ["http://localhost:9200"]